# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/grpc_generated/policy_sync.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'app/grpc_generated/policy_sync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$app/grpc_generated/policy_sync.proto\x12\x0f\x61\x65gis.policy.v1\"\x12\n\x10SubscribeRequest\"&\n\x0ePolicySnapshot\x12\x14\n\x0cjson_payload\x18\x01 \x01(\x0c\x32_\n\nPolicySync\x12Q\n\tSubscribe\x12!.aegis.policy.v1.SubscribeRequest\x1a\x1f.aegis.policy.v1.PolicySnapshot0\x01\x42JZHgithub.com/htunkhainglynn/aegis/reverse-proxy/internal/policypb;policypbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.grpc_generated.policy_sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZHgithub.com/htunkhainglynn/aegis/reverse-proxy/internal/policypb;policypb'
  _globals['_SUBSCRIBEREQUEST']._serialized_start=57
  _globals['_SUBSCRIBEREQUEST']._serialized_end=75
  _globals['_POLICYSNAPSHOT']._serialized_start=77
  _globals['_POLICYSNAPSHOT']._serialized_end=115
  _globals['_POLICYSYNC']._serialized_start=117
  _globals['_POLICYSYNC']._serialized_end=212
# @@protoc_insertion_point(module_scope)
