// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: app/grpc_generated/policy_sync.proto

package policypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_app_grpc_generated_policy_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_generated_policy_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_generated_policy_sync_proto_rawDescGZIP(), []int{0}
}

type PolicySnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonPayload   []byte                 `protobuf:"bytes,1,opt,name=json_payload,json=jsonPayload,proto3" json:"json_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySnapshot) Reset() {
	*x = PolicySnapshot{}
	mi := &file_app_grpc_generated_policy_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySnapshot) ProtoMessage() {}

func (x *PolicySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_generated_policy_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySnapshot.ProtoReflect.Descriptor instead.
func (*PolicySnapshot) Descriptor() ([]byte, []int) {
	return file_app_grpc_generated_policy_sync_proto_rawDescGZIP(), []int{1}
}

func (x *PolicySnapshot) GetJsonPayload() []byte {
	if x != nil {
		return x.JsonPayload
	}
	return nil
}

var File_app_grpc_generated_policy_sync_proto protoreflect.FileDescriptor

const file_app_grpc_generated_policy_sync_proto_rawDesc = "" +
	"\n" +
	"$app/grpc_generated/policy_sync.proto\x12\x0faegis.policy.v1\"\x12\n" +
	"\x10SubscribeRequest\"3\n" +
	"\x0ePolicySnapshot\x12!\n" +
	"\fjson_payload\x18\x01 \x01(\fR\vjsonPayload2_\n" +
	"\n" +
	"PolicySync\x12Q\n" +
	"\tSubscribe\x12!.aegis.policy.v1.SubscribeRequest\x1a\x1f.aegis.policy.v1.PolicySnapshot0\x01BJZHgithub.com/htunkhainglynn/aegis/reverse-proxy/internal/policypb;policypbb\x06proto3"

var (
	file_app_grpc_generated_policy_sync_proto_rawDescOnce sync.Once
	file_app_grpc_generated_policy_sync_proto_rawDescData []byte
)

func file_app_grpc_generated_policy_sync_proto_rawDescGZIP() []byte {
	file_app_grpc_generated_policy_sync_proto_rawDescOnce.Do(func() {
		file_app_grpc_generated_policy_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_grpc_generated_policy_sync_proto_rawDesc), len(file_app_grpc_generated_policy_sync_proto_rawDesc)))
	})
	return file_app_grpc_generated_policy_sync_proto_rawDescData
}

var file_app_grpc_generated_policy_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_grpc_generated_policy_sync_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: aegis.policy.v1.SubscribeRequest
	(*PolicySnapshot)(nil),   // 1: aegis.policy.v1.PolicySnapshot
}
var file_app_grpc_generated_policy_sync_proto_depIdxs = []int32{
	0, // 0: aegis.policy.v1.PolicySync.Subscribe:input_type -> aegis.policy.v1.SubscribeRequest
	1, // 1: aegis.policy.v1.PolicySync.Subscribe:output_type -> aegis.policy.v1.PolicySnapshot
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_grpc_generated_policy_sync_proto_init() }
func file_app_grpc_generated_policy_sync_proto_init() {
	if File_app_grpc_generated_policy_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_grpc_generated_policy_sync_proto_rawDesc), len(file_app_grpc_generated_policy_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_grpc_generated_policy_sync_proto_goTypes,
		DependencyIndexes: file_app_grpc_generated_policy_sync_proto_depIdxs,
		MessageInfos:      file_app_grpc_generated_policy_sync_proto_msgTypes,
	}.Build()
	File_app_grpc_generated_policy_sync_proto = out.File
	file_app_grpc_generated_policy_sync_proto_goTypes = nil
	file_app_grpc_generated_policy_sync_proto_depIdxs = nil
}
