// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: app/grpc_generated/policy_sync.proto

package policypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicySync_Subscribe_FullMethodName = "/aegis.policy.v1.PolicySync/Subscribe"
)

// PolicySyncClient is the client API for PolicySync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicySyncClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PolicySnapshot], error)
}

type policySyncClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicySyncClient(cc grpc.ClientConnInterface) PolicySyncClient {
	return &policySyncClient{cc}
}

func (c *policySyncClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PolicySnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PolicySync_ServiceDesc.Streams[0], PolicySync_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, PolicySnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicySync_SubscribeClient = grpc.ServerStreamingClient[PolicySnapshot]

// PolicySyncServer is the server API for PolicySync service.
// All implementations must embed UnimplementedPolicySyncServer
// for forward compatibility.
type PolicySyncServer interface {
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[PolicySnapshot]) error
	mustEmbedUnimplementedPolicySyncServer()
}

// UnimplementedPolicySyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicySyncServer struct{}

func (UnimplementedPolicySyncServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[PolicySnapshot]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedPolicySyncServer) mustEmbedUnimplementedPolicySyncServer() {}
func (UnimplementedPolicySyncServer) testEmbeddedByValue()                    {}

// UnsafePolicySyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicySyncServer will
// result in compilation errors.
type UnsafePolicySyncServer interface {
	mustEmbedUnimplementedPolicySyncServer()
}

func RegisterPolicySyncServer(s grpc.ServiceRegistrar, srv PolicySyncServer) {
	// If the following call pancis, it indicates UnimplementedPolicySyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicySync_ServiceDesc, srv)
}

func _PolicySync_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PolicySyncServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, PolicySnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicySync_SubscribeServer = grpc.ServerStreamingServer[PolicySnapshot]

// PolicySync_ServiceDesc is the grpc.ServiceDesc for PolicySync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicySync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegis.policy.v1.PolicySync",
	HandlerType: (*PolicySyncServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _PolicySync_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "app/grpc_generated/policy_sync.proto",
}
